### ISSUE TITLE
Missing space between log level and message when using ULOG_HIDE_FILE_STRING flag

### ISSUE THREAD

**Issue by hmars-t** [an-dr/microlog#19]
I m not sure if its intended, but I noticed that when using the `ULOG_HIDE_FILE_STRING` flag, there is no space between the log level and the actual log message, so it is printed like this:
`DEBUGinit_rdma_resources`.

**Comment by an-dr** [comment]
That's a bug. Will fix, thanks!

**Comment by an-dr** [comment]
@hmars-t seems to be fixed. Feel free to reopen if I missed something

**Comment by an-dr** [comment]
![image](https://github.com/user-attachments/assets/d0e8f29f-cfd8-4a34-b751-feb884e7fd2c)
